apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-child              # Child app name
  namespace: frontend
spec:
  project: frontend-team
  source:
    repoURL: https://github.com/avengers400/argocd-demos.git # Repo containing child apps(that you have forked and cloned earlier)
    targetRevision: main
    path: ui_approach/nginx      # path of Nginx app in `argocd-demos` repo
  destination:
    server: https://172.31.37.7:33893 # Replace with your Cluster Url, To get run: `argocd cluster list`
    namespace: frontend          # Deploys into default namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
